
package com.demoserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloServiceImpl", targetNamespace = "http://impl.demo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "f", targetNamespace = "http://impl.demo.com/", className = "com.demoserver.F")
    @ResponseWrapper(localName = "fResponse", targetNamespace = "http://impl.demo.com/", className = "com.demoserver.FResponse")
    @Action(input = "http://impl.demo.com/HelloServiceImpl/fRequest", output = "http://impl.demo.com/HelloServiceImpl/fResponse")
    public String f(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
